name: Release (stable from main)
on:
  push: { branches: [ main ] }
  workflow_dispatch:
permissions: { contents: write, pull-requests: write }
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.main.json
          skip-github-pull-request: false              # создаём Release-PR с CHANGELOG.md
          skip-github-release: false
